install.packages('devtools')
library(devtools)
install.packages("stringi",type="win.binary")
install_github("slidify", "ramnathv")
install_github("slidifyLibraries", "ramnathv")
library(slidify)
author("first_deck")
slidify('index.Rmd')
library(knitr)
browseURL('index.html')
